{
  "mode": "analyze",
  "root_dir": "data/",
  "dataset_root_dir": "/workspace/datasets/Minor_0507/",
  "analysis_presets": [
    "train_minor_0507",
    "test_minor_0507"
  ],
  "output_dir": "analysis_outputs/test_minor_0507_layer/",
  "batch_size": 1,
  "only_fps": 60,
  "input_fps": 30,
  "seed": 1234,
  "filter_valid_only": true,
  "layer_scales": [
    {
      "layer": 1,
      "scale": 1.0
    },
    {
      "layer": 2,
      "scale": 0.5
    },
    {
      "layer": 3,
      "scale": 0.25
    },
    {
      "layer": 4,
      "scale": 0.125
    }
  ],
  "layer_scatter_methods": [
    "ground_truth",
    "single",
    "combination",
    "splatting_zero_fill",
    "splatting_outside_in_4direction",
    "splatting_outside_in_4neighbor",
    "splatting_outside_in_8neighbor",
    "splatting_ground_truth_fill"
  ],
  "layer_bar_methods": [
    "ground_truth",
    "splatting_zero_fill",
    "splatting_outside_in_4direction",
    "splatting_outside_in_4neighbor",
    "splatting_outside_in_8neighbor",
    "splatting_ground_truth_fill"
  ],
  "metrics": {
    "enable_psnr": true,
    "enable_ssim": true,
    "enable_lpips": true,
    "enable_flip": false,
    "enable_psnr_div": false,
    "enable_flolpips": false,
    "enable_vfips": false,
    "lpips_net": "alex",
    "flip_dynamic_range": "LDR",
    "flip_pixels_per_degree": 67.0,
    "flip_tonemapper": "ACES",
    "psnr_div_divergence_threshold": 0.01,
    "flolpips_repo_path": null,
    "vfips_repo_path": null,
    "vfips_checkpoint_path": null,
    "vfips_clip_length": 12,
    "vfips_stride": 12
  }
}
