{
  "mode": "export",
  "model_name": "IFRNet_Residual_FlowApprox",
    "model_init_args": {
        "init_flow_layer": 4
  },
  "inference_preset": "train_minor_0507",
  "root_dir": "data/Minor_0507/",
  "dataset_root_dir": "/workspace/datasets/Minor_0507/",
  "checkpoint_path": "outputs/IFRNet_Residual_FlowApprox_Layer_4_Minor_0507_v2/checkpoints/best.pth",
  "out_dir": "inference_outputs/IFRNet_Residual_FlowApprox_Layer_4_Minor_0507_v2/videos",
  "seed": 1234,
  "batch_size": 1,
  "only_fps": 60,
  "input_fps": 30,
  "scale_factor": 1.0,
  "flow_approx_method": "combination",
  "fps": 60,
  "ignore_valid": true,
  "record": null,
  "target_mode": null,
  "export_grid": true,
  "layout": "basic",
  "tile_scale": 0.5,
  "pad": 8,
  "export_all": false,
  "export_vfi60": true,
  "single_files": []
}
