{
  "mode": "infer",
  "model_name": "IFRNet_Residual_FlowApprox",
  "model_init_args": {
    "init_flow_layer": 1,
    "convex_upsampling": false
  },
  "eval_convex_upsampling": false,
  "flow_approx_method": "splatting",
  "splatting_fill_strategy": "outside_in_8neighbor",
  "init_flow_downscale_strategy": "masked_area",
  "init_flow_mask_epsilon": 1.0e-6,
  "root_dir": "data/Minor_0507/",
  "dataset_root_dir": "/workspace/datasets/Minor_0507/",
  "inference_preset": [
    "train_minor_0507",
    "test_minor_0507"
  ],
  "checkpoint_path": "outputs/IFRNet_Residual_FlowApprox_1_Layer_TwoStage_Splat_8Neighbor_Minor_0605/checkpoints/best.pth",
  "output_dir": "inference_outputs/IFRNet_Residual_FlowApprox_1_Layer_TwoStage_Splat_8Neighbor_Minor_0605/",
  "seed": 1234,
  "batch_size": 1,
  "only_fps": 60,
  "input_fps": 30,
  "metrics": {
    "enable_psnr": true,
    "enable_ssim": true,
    "enable_lpips": true,
    "enable_flip": false,
    "enable_psnr_div": false,
    "lpips_net": "alex",
    "flip_dynamic_range": "LDR",
    "flip_pixels_per_degree": 67.0,
    "flip_tonemapper": "ACES",
    "psnr_div_divergence_threshold": 0.01
  },
  "scale_factor": 1.0,
  "flow_approx_method": "splatting",
  "flow_diff_threshold": 1.0,
  "flow_diff_percentile": 99.0,
  "save_topk_worst_psnr": 10,
  "save_topk_best_psnr": 5,
  "save_topk_largest_flow_diff": 10,
  "video": {
    "output_dir": "inference_outputs/IFRNet_Residual_FlowApprox_1_Layer_TwoStage_ZeroSplat_Minor_0603/videos",
    "fps": 60,
    "ignore_valid": true,
    "record_filter": null,
    "mode_filter": null,
    "export_grid": true,
    "tile_scale": 0.5,
    "pad": 8,
    "export_all": false,
    "export_vfi60": true,
    "single_files": []
  }
}
