{
  "mode": "infer",
  "model_name": "IFRNet_Residual_FlowApprox",
    "model_init_args": {
        "init_flow_layer": 4
  },
  "root_dir": "data/Minor_0507/",
  "dataset_root_dir": "/workspace/datasets/Minor_0507/",
  "inference_preset": "train_minor_0507",
  "checkpoint_path": "outputs/IFRNet_Residual_FlowApprox_0423/checkpoints/best.pth",
  "output_dir": "inference_outputs/IFRNet_Residual_FlowApprox_0423/",
  "seed": 1234,
  "batch_size": 1,
  "only_fps": 60,
  "input_fps": 30,
  "scale_factor": 1.0,
  "flow_approx_method": "combination",
  "flow_diff_threshold": 1.0,
  "flow_diff_percentile": 99.0,
  "save_topk_worst_psnr": 10,
  "save_topk_best_psnr": 5,
  "save_topk_largest_flow_diff": 10
}
