{
  "mode": "infer",
  "model_name": "IFRNet",
  "root_dir": "data/Minor_0507/",
  "dataset_root_dir": "/workspace/datasets/Minor_0507/",
  "inference_preset": [
    "train_minor_0507",
    "test_minor_0507"
  ],
  "checkpoint_path": "outputs/IFRNet_FineTuning_0611/checkpoints/latest.pth",
  "output_dir": "inference_outputs/IFRNet_FineTuning_0611/",
  "seed": 1234,
  "batch_size": 1,
  "only_fps": 60,
  "input_fps": 30,
  "scale_factor": 1.0,
  "flow_approx_method": "combination",
  "flow_diff_threshold": 1.0,
  "flow_diff_percentile": 99.0,
  "save_topk_worst_psnr": 10,
  "save_topk_best_psnr": 5,
  "save_topk_largest_flow_diff": 10,
  "save_train_frames": [
    "ARPG_2_4_Medium_5_0518",
    "ARPG_3_1_Medium_5_0058",
    "ARPG_3_2_Medium_5_0462",
    "ARPG_3_1_Medium_5_0018",
    "ARPG_2_4_Medium_5_0406",
    "ARPG_3_1_Medium_5_0324",
    "ARPG_3_2_Medium_5_0464",
    "ARPG_3_0_Medium_5_0794",
    "ARPG_2_4_Medium_5_0562",
    "ARPG_3_0_Medium_5_0460",
    "ARPG_3_2_Medium_5_0604",
    "ARPG_3_1_Medium_5_0042",
    "ARPG_3_2_Medium_5_0592",
    "ARPG_2_4_Medium_5_0408",
    "ARPG_3_1_Medium_5_0432",
    "ARPG_2_4_Medium_5_0680",
    "ARPG_3_0_Medium_5_0408",
    "ARPG_2_4_Medium_5_0400",
    "ARPG_2_4_Medium_5_0396",
    "ARPG_2_4_Medium_5_0392",
    "ARPG_2_4_Medium_5_0322",
    "ARPG_2_4_Medium_5_0712",
    "ARPG_2_4_Medium_5_0082"
  ],
  "save_test_frames": [
    "ARPG_3_3_Medium_5_0588"
  ],
  "save_train_frame_groups": {
    "large_motion_artifacts__improve_true": [
      "ARPG_2_4_Medium_5_0518",
      "ARPG_3_1_Medium_5_0058",
      "ARPG_3_2_Medium_5_0462"
    ],
    "large_motion_artifacts__improve_false": [
      "ARPG_3_1_Medium_5_0018",
      "ARPG_2_4_Medium_5_0406"
    ],
    "not_large_motion_high_psnr__improve_true": [
      "ARPG_3_1_Medium_5_0324",
      "ARPG_3_2_Medium_5_0464",
      "ARPG_3_0_Medium_5_0794"
    ],
    "not_large_motion_high_psnr__improve_false": [
      "ARPG_2_4_Medium_5_0562",
      "ARPG_3_0_Medium_5_0460",
      "ARPG_3_2_Medium_5_0604"
    ],
    "other_artifacts__improve_true": [
      "ARPG_3_1_Medium_5_0042",
      "ARPG_3_2_Medium_5_0592",
      "ARPG_2_4_Medium_5_0408"
    ],
    "other_artifacts__improve_false": [
      "ARPG_3_1_Medium_5_0432",
      "ARPG_2_4_Medium_5_0680",
      "ARPG_3_0_Medium_5_0408"
    ],
    "large_motion_high_psnr__improve_true": [
      "ARPG_2_4_Medium_5_0400",
      "ARPG_2_4_Medium_5_0396",
      "ARPG_2_4_Medium_5_0392"
    ],
    "large_motion_high_psnr__improve_false": [
      "ARPG_2_4_Medium_5_0322",
      "ARPG_2_4_Medium_5_0712",
      "ARPG_2_4_Medium_5_0082"
    ]
  },
  "save_test_frame_groups": {
    "large_motion_artifacts__improve_true": [],
    "large_motion_artifacts__improve_false": [
      "ARPG_3_3_Medium_5_0588"
    ],
    "not_large_motion_high_psnr__improve_true": [],
    "not_large_motion_high_psnr__improve_false": [],
    "other_artifacts__improve_true": [],
    "other_artifacts__improve_false": [],
    "large_motion_high_psnr__improve_true": [],
    "large_motion_high_psnr__improve_false": []
  },
  "video": {
    "output_dir": "inference_outputs/IFRNet_FineTuning_0611/videos",
    "fps": 60,
    "ignore_valid": true,
    "record_filter": null,
    "mode_filter": null,
    "export_grid": true,
    "tile_scale": 0.5,
    "pad": 8,
    "export_all": false,
    "export_vfi60": true,
    "single_files": []
  }
}
