{
  "mode": "infer",
  "model_name": "RIFE",
  "model_init_args": {
    "external_root": "src/models/external/RIFE"
  },
  "root_dir": "data/VFX_0416_oracleTime_clean",
  "dataset_root_dir": "/workspace/datasets/",
  "inference_preset": [
    "train_vfx_0416",
    "test_vfx_0416"
  ],
  "checkpoint_path": "src/models/external/RIFE/train_log",
  "output_dir": "inference_outputs/RIFE_Official",
  "seed": 1234,
  "batch_size": 1,
  "only_fps": 60,
  "input_fps": 30,
  "metrics": {
    "enable_psnr": true,
    "enable_ssim": true,
    "enable_lpips": true,
    "enable_flip": true,
    "enable_psnr_div": true,
    "enable_flolpips": true,
    "enable_vfips": true,
    "lpips_net": "alex",
    "flip_dynamic_range": "LDR",
    "flip_pixels_per_degree": 67.0,
    "flip_tonemapper": "ACES",
    "psnr_div_divergence_threshold": 0.01,
    "flolpips_repo_path": "/workspace/src/flolpips",
    "vfips_repo_path": "/workspace/src/VFIPS",
    "vfips_checkpoint_path": "/workspace/src/VFIPS/exp/eccv_ms_multiscale_v33/model.pytorch",
    "vfips_clip_length": 12,
    "vfips_stride": 12
  },
  "scale_factor": 1.0,
  "flow_approx_method": "combination",
  "flow_diff_threshold": 1.0,
  "flow_diff_percentile": 99.0,
  "save_topk_worst_psnr": 3,
  "save_topk_best_psnr": 0,
  "save_topk_largest_flow_diff": 0,
  "video": {
    "output_dir": "inference_outputs/RIFE_Official/videos",
    "fps": 60,
    "ignore_valid": true,
    "record_filter": null,
    "mode_filter": null,
    "export_grid": false,
    "tile_scale": 0.5,
    "pad": 8,
    "export_all": false,
    "export_vfi60": true,
    "single_files": []
  }
}
