{
  "mode": "train",
  "model_name": "IFRNet_Residual_FlowApprox",
  "flow_approx_method": "splatting",
  "splatting_fill_strategy": "outside_in_4direction",
  "init_flow_downscale_strategy": "bilinear",
  "init_flow_mask_epsilon": 1.0e-6,
    "model_init_args": {
        "init_flow_layer": 1
  },
  "root_dir": "data/VFX_0416_oracleTime_clean/",
  "dataset_root_dir": "/workspace/datasets/",
  "train_preset": "train_vfx_0416",
  "test_preset": "test_vfx_0416",
  "epochs": 150,
  "eval_interval": 5,
  "lr_start": 1e-4,
  "lr_end": 1e-5,
  "seed": 1234,
  "batch_size": 16,
  "output_dir": "outputs/IFRNet_Residual_FlowApprox_1_Layer_TwoStage_Splat_4Direction_Bilinear_0624_OracleTime",
  "only_fps": 60,
  "input_fps": 30,
  "metrics": {
    "enable_psnr": true,
    "enable_ssim": true,
    "enable_lpips": true,
    "enable_flip": true,
    "enable_psnr_div": false,
    "enable_flolpips": false,
    "enable_vfips": false,
    "lpips_net": "alex",
    "flip_dynamic_range": "LDR",
    "flip_pixels_per_degree": 67.0,
    "flip_tonemapper": "ACES",
    "psnr_div_divergence_threshold": 0.01,
    "flolpips_repo_path": "/workspace/src/flolpips",
    "vfips_repo_path": "/workspace/src/VFIPS",
    "vfips_checkpoint_path": "/workspace/src/VFIPS/exp/eccv_ms_multiscale_v33/model.pytorch",
    "vfips_clip_length": 12,
    "vfips_stride": 12
  },
  "resume_path": "outputs/IFRNet_Residual_FlowApprox_1_Layer_TwoStage_Splat_4Direction_Bilinear_0624_OracleTime/checkpoints/latest.pth",
  "pretrained_checkpoint_path": null
}
