{
  "mode": "train",
  "model_name": "IFRNet_Residual_FlowApprox",
    "model_init_args": {
        "init_flow_layer": 1
  },
  "root_dir": "data/Minor_0507/",
  "dataset_root_dir": "/workspace/datasets/Minor_0507/",
  "train_preset": "train_minor_0507",
  "test_preset": "test_minor_0507",
  "epochs": 50,
  "eval_interval": 1,
  "lr_start": 1e-4,
  "lr_end": 8.5e-5,
  "seed": 1234,
  "batch_size": 16,
  "output_dir": "outputs/IFRNet_Residual_FlowApprox_1_Layer_TwoStage_ZeroSplat_Minor_0603",
  "only_fps": 60,
  "input_fps": 30,
  "metrics": {
    "enable_psnr": true,
    "enable_ssim": true,
    "enable_lpips": true,
    "lpips_net": "alex"
  },
  "flow_approx_method": "splatting",
  "resume_path": null,
  "pretrained_checkpoint_path": "outputs/IFRNet_Residual_0416/checkpoints/best.pth",
  "sample_train_frames": [
    "ARPG_3_0_Medium_5_0404",
    "ARPG_3_1_Medium_5_0452"
  ],
  "sample_test_frames": [
    "ARPG_3_3_Medium_5_0654"
  ],
  "sample_interval_epoch": 1
}
