{
  "mode": "train",
  "model_name": "IFRNet",
  "root_dir": "data/Minor_0507/",
  "dataset_root_dir": "/workspace/datasets/Minor_0507/",
  "train_preset": "train_minor_0507",
  "test_preset": "test_minor_0507",
  "epochs": 100,
  "eval_interval": 5,
  "lr_start": 2e-5,
  "lr_end": 1e-5,
  "seed": 1234,
  "batch_size": 16,
  "output_dir": "outputs/IFRNet_FineTuning_0611/",
  "only_fps": 60,
  "input_fps": 30,
  "metrics": {
    "enable_psnr": true,
    "enable_ssim": true,
    "enable_lpips": true,
    "enable_flip": false,
    "lpips_net": "alex",
    "flip_dynamic_range": "LDR",
    "flip_pixels_per_degree": 67.0,
    "flip_tonemapper": "ACES"
  },
  "resume_path": null,
  "pretrained_checkpoint_path": "src/models/external/IFRNet/checkpoints/IFRNet/IFRNet_Vimeo90K.pth",
  "sample_train_frames": [
    "ARPG_3_0_Medium_5_0404",
    "ARPG_3_1_Medium_5_0452"
  ],
  "sample_test_frames": [
    "ARPG_3_3_Medium_5_0654"
  ],
  "sample_interval_epoch": 5
}
