{
  "mode": "train",
  "model_name": "IFRNet",
  "root_dir": "data/VFX_0416_oracleTime_clean/",
  "dataset_root_dir": "/workspace/datasets/",
  "train_preset": "train_vfx_0416",
  "test_preset": "test_vfx_0416",
  "epochs": 150,
  "eval_interval": 5,
  "lr_start": 2e-5,
  "lr_end": 1e-5,
  "seed": 1234,
  "batch_size": 32,
  "output_dir": "outputs/IFRNet_FineTuning_0625_oracleTime/",
  "only_fps": 60,
  "input_fps": 30,
  "resume_path": null,
  "pretrained_checkpoint_path": "src/models/external/IFRNet/checkpoints/IFRNet/IFRNet_Vimeo90K.pth",
  "metrics": {
    "enable_psnr": true,
    "enable_ssim": true,
    "enable_lpips": true,
    "lpips_net": "alex"
  }
}
