{
  "mode": "train",
  "model_name": "IFRNet_Residual",
    "model_init_args": {
        "init_flow_layer": 4
  },
  "root_dir": "data/VFX_0416_oracleTime_clean/",
  "dataset_root_dir": "/workspace/datasets/",
  "train_preset": "train_vfx_0416",
  "test_preset": "test_vfx_0416",
  "epochs": 150,
  "eval_interval": 5,
  "lr_start": 1e-4,
  "lr_end": 1e-5,
  "seed": 1234,
  "batch_size": 32,
  "output_dir": "outputs/IFRNet_Residual_4_Layer_Scratch_0624_oracleTime",
  "only_fps": 60,
  "input_fps": 30,
  "metrics": {
    "enable_psnr": true,
    "enable_ssim": true,
    "enable_lpips": true,
    "lpips_net": "alex"
  },
  "resume_path": null,
  "pretrained_checkpoint_path": null
}
