{
  "mode": "train",
  "model_name": "IFRNet_Residual_FlowApprox",
  "flow_approx_method": "splatting",
  "splatting_fill_strategy": "outside_in_4direction",
  "init_flow_downscale_strategy": "bilinear",
  "init_flow_mask_epsilon": 1.0e-6,
    "model_init_args": {
        "init_flow_layer": 1
  },
  "root_dir": "data/VFX_0416_oracleTime_clean",
  "dataset_root_dir": "/workspace/datasets/",
  "train_preset": "train_vfx_0416",
  "test_preset": "test_vfx_0416",
  "epochs": 150,
  "eval_interval": 5,
  "lr_start": 1e-4,
  "lr_end": 1e-5,
  "seed": 1234,
  "batch_size": 32,
  "output_dir": "outputs/IFRNet_Residual_FlowApprox_1_Layer_TwoStage_Splat_4Direction_MaskedArea_0624_oracleTime",
  "only_fps": 60,
  "input_fps": 30,
  "metrics": {
    "enable_psnr": true,
    "enable_ssim": true,
    "enable_lpips": true,
    "lpips_net": "alex"
  },
  "resume_path": null,
  "pretrained_checkpoint_path": "outputs/IFRNet_Residual_4_Layer_Scratch_0624_oracleTime/checkpoints/best.pth"
}
